### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by windsurfer** [composer/getcomposer.org#101]
[getcomposer.org/blob/master/web/installer](https://github.com/composer/getcomposer.org/blob/master/web/installer) implies that it must be distributed with a LICENSE file, but it is not located in this repo.

**Comment by Seldaek** [comment]
True that. Fixed in https://github.com/composer/getcomposer.org/commit/1e71bb1a1d27de05b8393383c16a63f55d916d8f
