### ISSUE TITLE
web/installers should warn/check for git

### ISSUE THREAD

**Issue by ryanaslett** [composer/getcomposer.org#108]
In building some php docker containers for drupalci, we had composer install via the automated method, but we didnt install git. Without git there were some functions that worked fine from outside the container but broke inside the container (figuring out the version of drupal from the branch name).

Anyhow, would be nice if the installer threw a warning or something that said "git's not required, but its a good idea"

**Comment by alcohol** [comment]
Not sure I agree. The installer checks for installation requirements. Having git is not really an installation requirement. Composer itself could (or should?) hint at runtime about the lack of git availability though.

**Comment by ryanaslett** [comment]
I saw that there were both warnings/and errors in the script, and things like having xdebug enabled throw a warning, but I agree that this would probably be better in the runtime itself, since composer may have been installed using other methods that do not involve web/installer

**Comment by Seldaek** [comment]
We check and warn for git not being there at runtime when you actually would've needed git. We can't just complain about git not being there all the time, because some people don't use git at all and that's fine.
