### ISSUE TITLE
Sorry, but what's the point of this file?

### ISSUE THREAD

**Issue by blaasvaer** [composer/getcomposer.org#111]
How do I use it, in other words?

**Comment by blaasvaer** [comment]
Following the instructions on getcomposer.org
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

throw this at me:
Warning: copy(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in Command line code on line 1

Warning: copy(): Failed to enable crypto in Command line code on line 1

Warning: copy(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1

Where to go from here?

**Comment by stof** [comment]
fix the configuration of your PHP setup so that openssl can access certificates. The issue you get is that your PHP cannot read a HTTPS URL.

**Comment by blaasvaer** [comment]
I rum MAMP, how do I do that?

**Comment by Seldaek** [comment]
Please search for similar issues on https://github.com/composer/composer - you'll probably find a gazillion tips on how to possibly fix this.
