### ISSUE TITLE
Composer don't work over php 7 ?

### ISSUE THREAD

**Issue by aymard-pro** [composer/getcomposer.org#112]
Hello guy,

I'm using `PHP 7.0.19` and when I'm trying to use composer, I've got `ErrorException` such `php_uname() has been disabled for security reasons ` and many others.

**Comment by Seldaek** [comment]
PHP7 is not the problem, composer is not the problem, your php.ini settings are the problem. You probably have disabled_functions set to include php_uname and others. I fixed that for php_uname so if you run `composer self-update --snapshot` it should now work, but if you have other disabled functions you might still have issues.

**Comment by aymard-pro** [comment]
Ok, I removed it from disabled_functions (in php CLI ini file) and it work fine. Thanks
