### ISSUE TITLE
Where are the release tags?

### ISSUE THREAD

**Issue by uberhacker** [composer/getcomposer.org#116]
Shouldn't we be tagging a new release for each new version?  For example, my expectation would be a tag of `1.4.2` for the latest stable release.

**Comment by alcohol** [comment]
Like this one? https://github.com/composer/composer/releases/tag/1.4.2

**Comment by alcohol** [comment]
Or do you mean, tagging this repository?

**Comment by uberhacker** [comment]
Sorry, I didn't realize these projects were related?  Why two projects? :)

**Comment by alcohol** [comment]
This repository is purely for the `getcomposer.org` domain/website itself. It hosts the documentation and what not. But not the actual source code of the `composer` binary.

There is `composer/composer` for the core source code, and a few other repositories (`composer/semver`, `composer/spdx-licenses`, etc for internal components).

**Comment by uberhacker** [comment]
@alcohol: Gotcha, thank you for the explanation.

**Comment by stof** [comment]
@alcohol technnically, it does not even host the documentation (which is alongside the source code in composer/composer). It only hosts the code responsible for displaying the doc on the web

**Comment by uberhacker** [comment]
@stof: What do you mean by _displaying the doc on the web_?  Does this mean only the html and supporting assets use to display the getcomposer.org site?

**Comment by stof** [comment]
Well, the HTML is generated on-the-fly from the markdown source (which are in the composer/composer repo). This repo contains the small app written with the Silex framework which exposes the website, with a homepage (maintained here) and the markdown conversion for doc pages.

**Comment by stof** [comment]
oh, and it also contains the script used to generate a PDF version of the doc (using the Markdown files as source), but this script is broken since a while (the PDF version of the doc is not available anymore because of that)
