### ISSUE TITLE
Problem with xampp on E: ?

### ISSUE THREAD

**Issue by dassoun** [composer/getcomposer.org#120]
Hello!

I am trying to run the installer with xampp installed on E:.
The 1rst error message I have is:

> The PHP exe file you specified did not run correctly:
> E:\Programmes\xampp\php\php.exe
> 
> The php.ini used by your command-line PHP is: E:\Programmes\xampp\php\php.ini
> 
> A setting in your php.ini could be causing the problem: Either the 'extension_dir' value is incorrect or the dll does not exist.
> 
> Program Output:
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_bz2.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_curl.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_fileinfo.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_gd2.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_gettext.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_mbstring.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_exif.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_mysql.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_mysqli.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_pdo_mysql.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_pdo_sqlite.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_pgsql.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '\Programmes\xampp\php\ext\php_openssl.dll' - Le module spécifié est introuvable.
>  in Unknown on line 0
> Warning: Cannot open '\Programmes\xampp\php\extras\browscap.ini' for reading in Unknown on line 0

It seems that a part of the problem can be solved by putting

> extension_dir = "E:\Programmes\xampp\php\ext"

rather than the initial 

> extension_dir = "\Programmes\xampp\php\ext"

in php.ini

With this change, the error becomes:

> The PHP exe file you specified did not run correctly:
> E:\Programmes\xampp\php\php.exe
> 
> The php.ini used by your command-line PHP is: E:\Programmes\xampp\php\php.ini
> 
> Program Output:
> Warning: Cannot open '\Programmes\xampp\php\extras\browscap.ini' for reading in Unknown on line 0

I tried to put 

> [browscap]
> browscap = "E:\xampp\php\extras\browscap.ini"

in php.ini, but the error is still the same.

How could I solve it, please?

Regards

**Comment by alcohol** [comment]
Wrong repository. Please report this problem on the windows installer repository or on the main composer repository (if you are installing from the command line).
