### ISSUE TITLE
Increase download timeout

### ISSUE THREAD

**Issue by sebastien-fauvel** [composer/getcomposer.org#122]
See https://github.com/composer/composer/issues/7027

In [`getMergedStreamContext`](https://github.com/composer/getcomposer.org/blob/master/web/installer#L1320), could you please set the timeout explicitly instead of relying on the default timeout, which is [`default_socket_timeout`](http://php.net/manual/en/filesystem.configuration.php#ini.default-socket-timeout) for http streams?

This can be done by adding for instance:
```php
$options['http']['timeout'] = 3600;
```

Thank you!

**Comment by alcohol** [comment]
An hour..? Just how bad exactly was the network you were using? This sounds like a very exceptional edge-case.
