### ISSUE TITLE
issue with installing missing dependencies for composer install command.

### ISSUE THREAD

**Issue by ajita-asthana** [composer/getcomposer.org#125]
When I run the composer install command.
I get the following output.
![screen shot 2018-07-10 at 8 38 06 am](https://user-images.githubusercontent.com/16641779/42519282-4d49f358-8481-11e8-86ad-22d5cba5c325.png)
I am having issues with installing the packages with their specified versions.

**Comment by ajita-asthana** [comment]
You mean a command like sudo apt-get install package-name

**Comment by alcohol** [comment]
Closing this issue now as this is also the wrong repository to ask for support. Please use [composer/composer](https://github.com/composer/composer) for any further questions.
