### ISSUE TITLE
Update proposal for getcomposer.org/installer

### ISSUE THREAD

**Issue by BernardZijlstra** [composer/getcomposer.org#126]
The install script for composer (https://getcomposer.org/installer) could use some updates. 

Function getTlsStreamContextDefaults() in class HttpClient uses an aray of ciphers which also include older less secure ciphers like RC4. My proposal would be to decrease the cipher list and use TLS version 1.0 as the lower boundary.

The Mozilla CA Root bundle included in the bottom part of the installer script is dated at june 2017. It could do with an update because a lot has changed sinds then.

**Comment by alcohol** [comment]
PRs are welcome
