### ISSUE TITLE
Fail to use OpenSSL 1.1.1

### ISSUE THREAD

**Issue by dertin** [composer/getcomposer.org#129]
This conditional seems not to work:
https://github.com/composer/getcomposer.org/blob/4d2ef40109bfbec0f9b8b39f12f260fb6e80befa/web/installer#L649

OpenSSL 1.1.1
Composer v1.7.2

**Comment by alcohol** [comment]
See https://github.com/composer/getcomposer.org/pull/128

**Comment by Seldaek** [comment]
Closed by #128
