### ISSUE TITLE
Errors missing due to display_errors=0

### ISSUE THREAD

**Issue by mbrodala** [composer/getcomposer.org#133]
The [Composer installer script](https://github.com/composer/getcomposer.org/blob/72bb6f65aa902c76c7ca35514f58cf79a293657d/web/installer) can fail silently in case e.g. the memory limit has been configured wrongly and `display_errors=0` is active:

```
$ curl -sS https://getcomposer.org/installer | php -dmemory_limit=512 -ddisplay_errors=0
All settings correct for using Composer
Downloading...
$
```

In this case the memory limit has been set to 512 bytes instead of 512 megabytes:

```
$ curl -sS https://getcomposer.org/installer | php -dmemory_limit=512
All settings correct for using Composer
Downloading...

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 479232 bytes) in Standard input code on line 1202
$
```

Would it be an option to add `ini_set('display_errors', 1);` to the installer script to ensure all errors are displayed?

**Comment by alcohol** [comment]
I don't see any downsides to be honest.. what about you @Seldaek ?

**Comment by Seldaek** [comment]
Sounds reasonable yes..

**Comment by alcohol** [comment]
@mbrodala feel free to submit a PR :-)
