### ISSUE TITLE
Installer Option install-dir does not seem to work

### ISSUE THREAD

**Issue by vismagine** [composer/getcomposer.org#153]
The Installer Option --install-dir to install composer to a specific directory and providing a target directory does not seem to work. Error message:

"The defined install dir (~/html/test/) does not exist."

We double checked permissions, path and availability of the mentioned directory but still get the message.

**Comment by Seldaek** [comment]
Probably due to your use of `~`. What is the full command you executed? Did you quote the string in a way that ~ did not get expanded by your shell perhaps? Because php sure has no idea what `~/html` means
