### ISSUE TITLE
Allow to programmatically install specific major version

### ISSUE THREAD

**Issue by gisostallenberg** [composer/getcomposer.org#155]
The installer that can be used to [install composer programmatically](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md#how-do-i-install-composer-programmatically-) allows an option `--version`, but that needs to be a full version. The self-update allows to install a version using either `--1` or `--2`. We would like to switch the version used in our CI/CD intentionally (and lock to 1 for the moment) and not have detailed version info such as `1.10.7`  in the scripts used in our CI/CD.
The [API providing the versions](https://getcomposer.org/versions) that are available can already be used to get the specific version if a major version is provided in `--version`.
I suggest to allow a specific version or a major version and in case the script is called with a major version it should look up the specific version for that major.

I'm happy to provide you with a PR if you are interested.

```sh
#!/bin/sh

EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi

php composer-setup.php --quiet --version=${COMPOSER_MAJOR_VERSION:-1}
RESULT=$?
rm composer-setup.php
exit $RESULT
```

**Comment by Seldaek** [comment]
If you want to send a PR please do, but ideally this should be `--1` and `--2` flags as well to mimick self-update, instead of `--version -1`.

**Comment by Seldaek** [comment]
Just overriding $channel  around https://github.com/composer/getcomposer.org/blob/master/web/installer#L62 to `1` or `2` if those flags are passed should be enough.

As there are channels defined in https://getcomposer.org/versions - but then much like self-update does in https://github.com/composer/composer/blob/master/src/Composer/SelfUpdate/Versions.php#L61 , it should reset that to stable if --1 or --2 is passed, so that a self-update following an install with --2 or --1 would go back to just installing the stable channel.

**Comment by gisostallenberg** [comment]
> As there are channels defined in https://getcomposer.org/versions - but then much like self-update does in https://github.com/composer/composer/blob/master/src/Composer/SelfUpdate/Versions.php#L61 , it should reset that to stable if --1 or --2 is passed, so that a self-update following an install with --2 or --1 would go back to just installing the stable channel.

I'm not really sure what you mean here. Self update with --2 or --1 would just install that major, right?

**Comment by Seldaek** [comment]
Yes, I mean that if you run the installer script with --1 or --2, then run a self-update without any flag, it should behave the same as if you ran a self-update --1/--2 and then self-update without flag, i.e. update with the stable channel. Does that clarify? :)

**Comment by gisostallenberg** [comment]
Ok, I'll try to create a PR based on this information.
