### ISSUE TITLE
i have this issues in installing composer please help me to solve it

### ISSUE THREAD

**Issue by farshidahmadianpin** [composer/getcomposer.org#162]
The Composer installer script was not successful [exit code 1].

Your proxy settings may be causing this error.

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: No connection could be made because the target machine actively refused it.

**Comment by Seldaek** [comment]
@farshidahmadianpin sorry but that looks like a network error which we can not do much about. Maybe try using a VPN?
