### ISSUE TITLE
Use standards-compliant value in User-Agent HTTP header field sent by Composer installer

### ISSUE THREAD

**Issue by nicoroeser** [composer/getcomposer.org#166]
Currently, the Composer installer identifies with an incorrect value in the `User-Agent` header field when it sends HTTP requests.

Spaces are not allowed, and the version is separated from the user agent product identifier by a slash. This is explained in [RFC 7231 (“Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content”)](https://tools.ietf.org/html/rfc7231) [section 5.5.3 (“User-Agent”)](https://tools.ietf.org/html/rfc7231#section-5.5.3). (`token` is defined in [RFC 7230 (“Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing”)](https://tools.ietf.org/html/rfc7230) [section 3.2.6 (“Field Value Components”)](https://tools.ietf.org/html/rfc7230#section-3.2.6).)

**Comment by Seldaek** [comment]
Ah thanks, wasn't aware of that restriction.

**Comment by Seldaek** [comment]
cc @johnstevenson btw just FYI

**Comment by johnstevenson** [comment]
@Seldaek Thanks.
