### ISSUE TITLE
Download page does not reference "getting started"

### ISSUE THREAD

**Issue by loop54-christoffer** [composer/getcomposer.org#172]
It's easy for a new user to go directly to the Download page and skip the Getting Started page. This results in the new user following much more complicated instructions for installation than what is necessary on most operating systems.

A section early on the page saying something like

> # Install Composer
>
> The recommended way to install composer on your operating system may not include downloading it from here. Please check the Getting Started page for further installation instructions.
>
> This page is meant for advanced users who want full control over the installation procedure.

would probably help direct these users to the right place.

**Comment by stof** [comment]
The source code for the website is at https://github.com/composer/getcomposer.org. This could be added

**Comment by loop54-christoffer** [comment]
Yes. I can create a PR for it if there's agreement around the general idea.

**Comment by Seldaek** [comment]
Sounds reasonable to me, feel free to PR, it's on the download.html.twig file here.
