### ISSUE TITLE
Add major version selection to installer help and download page

### ISSUE THREAD

**Issue by pixelbrackets** [composer/getcomposer.org#174]
Commit ab97ebf56f83cb4dbbcd3087d8648a45d6fcdb22 introduced an option to install specific major versions programmatically, eg. `php composer-setup.php --1`.

> A PR for the docs to show the usage in 'How do I install Composer programmatically?' will be created in the composer documentation

This doc was added to the [self-update](https://getcomposer.org/doc/03-cli.md#self-update-selfupdate-) command.

It is missing in the installer `help` and the Composer download page however.

**Comment by Seldaek** [comment]
I am not sure about this.. I don't really want to encourage people to keep installing v1 as we are not supporting it anymore. I don't think adding these instructions all over the place and needing to clean them up later makes a ton of sense.

**Comment by pixelbrackets** [comment]
Hey, I don't see an encouragement to install a legacy version here. :) It's just a documentation of existing options.

My motivation to use the option:
- Follow the same dependency pattern for Composer as I do in all packages. Don't fetch `master`, but a specific major version instead. I used the »latest stable« version until recently and had to rollback to 1.x because right now in this very moment several dependencies have incompatibilities with Composer 2.0, causing broken CI builds. I'm sure I'm not the only one looking for a temporary rollback in CI builds → It's imho a better experience for users to not “hide” this option right now.

My motivation to add this to the docs:
- Already documented in the [self-update](https://getcomposer.org/doc/03-cli.md#self-update-selfupdate-) command, mentioned in the official release announcement on Private Packagist](https://blog.packagist.com/composer-2-0-is-now-available/), but missing on the most important place, the installer itself → Which I use to setup CI build scripts etc.

**Comment by Seldaek** [comment]
Right, fair enough, although I don't like people pinning old releases because some will likely forget and keep using v1 for ages, I guess it's a necessary evil during the transition period.

**Comment by Seldaek** [comment]
Closing here, thanks!
