### ISSUE TITLE
Installer changed from installing v2 to v1 by default

### ISSUE THREAD

**Issue by juliushaertl** [composer/getcomposer.org#177]
We encountered an issue with the installer no longer downloading version 2 of composer by default since  roughly an hour ago. From a quick look at the installer code it picks the stable channel if not otherwise specified.

https://getcomposer.org/versions reports stable being the newest 1.10.19 release while i would assume it was 2.0.x before the 1.10.19 release came out. At least that is what our CI installed before.

Basically the steps from https://getcomposer.org/download/ no longer install 2.0.8:
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

**Comment by Seldaek** [comment]
Fixed now, sorry about that.

**Comment by juliushaertl** [comment]
Thank you very much :+1:
