### ISSUE TITLE
Mcrypt PHP extension required.

### ISSUE THREAD

**Issue by amekirii** [composer/getcomposer.org#200]
eng : how to solve it?
indo : cara ngatasinya gimana? mau bikin laravel soalny

**Comment by Seldaek** [comment]
What are you seeing? It should not be required as far as I know.

**Comment by claykalmus** [comment]
have you try this?
https://stackoverflow.com/questions/16830405/laravel-requires-the-mcrypt-php-extension

**Comment by GhostBG90** [comment]
__-_ _✍️“👍”

**Comment by stof** [comment]
This repo is the repo for the getcomposer.org website, which is not based on Laravel at all.
I suspect that you opened this issue in the wrong issue tracker.
