### ISSUE TITLE
getcomposer.org is throwing 404 and 500 errors when attempting to download 

### ISSUE THREAD

**Issue by nurdism** [composer/getcomposer.org#210]
https://getcomposer.org/ is having some issues, I'm having trouble downloading composer. The website is throwing 404 and 500 errors. Opened this issue to notify the maintainers.

**Comment by mbabker** [comment]
It's the same root issue as #209, the download page fails hard when the signature for the latest release is missing it looks like.

**Comment by Seldaek** [comment]
Yup, fixed now sorry.
