### ISSUE TITLE
Installer deprecation warning on failure: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated

### ISSUE THREAD

**Issue by dzuelke** [composer/getcomposer.org#216]
If the install dir is not writable, `installer`/`composer-setup.php` throws a deprecation warning:

```ShellSession
% php composer-setup.php --install-dir=/usr/local/bin --filename=composer
All settings correct for using Composer
PHP Deprecated:  file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in composer-setup.php on line 1197

Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in composer-setup.php on line 1197
The installation directory "/usr/local/bin" is not writable
```

**Comment by Elimuhub-coder** [comment]
![Screenshot_20230810-225156](https://github.com/composer/getcomposer.org/assets/103851522/954f5fc4-cd5e-4735-b4ed-34db77a2a11d)

**Comment by unrulyest** [comment]
> If the install dir is not writable, `installer`/`composer-setup.php` throws a deprecation warning:
> 
> ```
> % php composer-setup.php --install-dir=/usr/local/bin --filename=composer
> All settings correct for using Composer
> PHP Deprecated:  file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in composer-setup.php on line 1197
> 
> Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in composer-setup.php on line 1197
> The installation directory "/usr/local/bin" is not writable
> ```

% php composer-setup.php --install-dir=/usr/local/bin --filename=composer
All settings correct for using Composer
PHP Deprecated:  file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in composer-setup.php on line 1197

Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in composer-setup.php on line 1197
The installation directory "/usr/local/bin" is not writable
