### ISSUE TITLE
Do we have a documentation for packages.json - field source?

### ISSUE THREAD

**Issue by matjung** [composer/getcomposer.org#218]
Hello Getcomposer Authors and Community
https://getcomposer.org/doc/05-repositories.md#packages

Extract from documentation:
The @composer.json marker would be the contents of the composer.json from that package version including as a minimum:
    name
    version
    dist or source

I try to find the documentation for the source field.

**Comment by Seldaek** [comment]
See https://github.com/composer/getcomposer.org/issues/219#issuecomment-1602342290
