### ISSUE TITLE
Windows Installer didn't install the composer.phar!!

### ISSUE THREAD

**Issue by SimantaRajSarma** [composer/getcomposer.org#228]
hey, I Installed the composer with the windows Installer. when I run `php composer.phar` in cmd. it returned `Could not open input file: composer.phar`. Can anyone tell me what happened??

**Comment by Seldaek** [comment]
You probably should run simply `composer` on CLI then if you installed it globally with the installed. `php composer.phar` is when you have a composer.phar in the current directory.
