### ISSUE TITLE
Include the installer into the github releases

### ISSUE THREAD

**Issue by vivere-dally** [composer/getcomposer.org#229]
[On this page](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md), it is mentioned that we can install composer by running: `wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet`.

However, to stay up to date, we have to keep monitoring that hash to point to the latest version. It would be helpful to include the installer in the release assets of github, [allowing users to point to the latest version automatically](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release).

**Comment by Seldaek** [comment]
But if you automatically grab the latest, you are not ensuring any integrity, so IMO it is better to rely on an exact commit hash.
