### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by whoisnobody** [composer/getcomposer.org#231]
Hello,
For about 30 minutes I have a problem with installing composer using installer:
curl -s https://raw.githubusercontent.com/composer/getcomposer.org/main/web/installer | php8.1 -- --install-dir=/usr/local/bin/ --filename=composer

PHP Parse error:  syntax error, unexpected token "::", expecting variable in Standard input code on line 1341

**Comment by Seldaek** [comment]
It's fixed now, sorry for the trouble 😅  It was simply a typo I missed in an installer script change, the composer.phar file was fine.
