### ISSUE TITLE
Installer syntax error in HttpClient

### ISSUE THREAD

**Issue by GamesmenJordan** [composer/getcomposer.org#232]
Changes added in a86d1c0b5edd3e71b8a7e746ddb47c19a3b43c76 to HttpClient cause a syntax error (at least in PHP 8.1).

`PHP Parse error:  syntax error, unexpected token "::", expecting variable in /tmp/composer-setup.php on line 1341`

Offending line is how this static variable is declared.

```php
class HttpClient {

    /** @var null|string */
    private static self::$caPath;

```

**Comment by siwa-tkapplmueller** [comment]
As a quick workaround i used a commit from two weeks ago - so with https://raw.githubusercontent.com/composer/getcomposer.org/66b5bbc00537a98681d27a46d86df800e700db08/web/installer instead of https://getcomposer.org/installer the installer works.
