### ISSUE TITLE
getcomposer script fails with PHP 8.1.3

### ISSUE THREAD

**Issue by jokesterfr** [composer/getcomposer.org#233]
We noticed this early afternoon, our CIs are failing.
We do use this in our Makefiles:

```makefile
composer.phar:
	@php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');";
	@php composer-setup.php;
	@php -r "unlink('composer-setup.php');";
```

The execution of composer-setup.php fails:

```
❯ php ./composer-setup.php 
PHP Parse error:  syntax error, unexpected token "::", expecting variable in ~/workspace/my-project/composer-setup.php on line 1341

Parse error: syntax error, unexpected token "::", expecting variable in ~/workspace/my-project/composer-setup.php on line 1341
```

Indeed the `installer` script has a syntax error, as below:

```php
class HttpClient {

    /** @var null|string */
    private static self::$caPath;
```

This property was recently modified, is there an interface issue with HttpClient?
Best,

--
The PrestaShop team

**Comment by GamesmenJordan** [comment]
I guess we all decided to report this issue at the same time.

#232

**Comment by Seldaek** [comment]
It's fixed now, sorry for the trouble 😅  It was simply a typo I missed in an installer script change, the composer.phar file was fine.
