### ISSUE TITLE
Non-optimal status code for redirect to https 

### ISSUE THREAD

**Issue by jrfnl** [composer/getcomposer.org#239]
_Context: noticed this via a dead link/URL redirect checker._

When requesting `http://getcomposer.org/` it redirects to `https://getcomposer.org/` with status code `302` (= temporary redirect).

To verify, run `curl -v http://getcomposer.org/`

I believe it would be more optimal to redirect with a `301` (= permanent redirect) status code.

Not sure where to change this, so just opening this issue to draw attention to this.

**Comment by frcofrancisco444-blip** [comment]
> _Context: noticed this via a dead link/URL redirect checker._
> 
> When requesting `http://getcomposer.org/` it redirects to `https://getcomposer.org/` with status code `302` (= temporary redirect).
> 
> To verify, run `curl -v http://getcomposer.org/`
> 
> I believe it would be more optimal to redirect with a `301` (= permanent redirect) status code.
> 
> Not sure where to change this, so just opening this issue to draw attention to this.
