### ISSUE TITLE
Logo is a conductor, not a composer

### ISSUE THREAD

**Issue by davereid** [composer/getcomposer.org#36]
The logo is very clearly a conductor, not a composer. He is holding a baton and appearing to be flailing his arms in a typical fashion during a performance, which a composer would not do while composing music. I feel this is deceiving to those with musical backgrounds and should be corrected, unless the project name can be changed.

![](http://getcomposer.org/img/logo-composer-transparent.png)

**Comment by GRMule** [comment]
I came here to cry about the conductor in the logo, and see that I'm not alone. Snuffle. Oh well, back to end usering my code... errimean writing my code.

We tried, pedants, we tried.

**Comment by moniuch** [comment]
@GRMule ...Before you yell at musicians confusing Java and JavaScript... ;-)

**Comment by WinnieB** [comment]
I've been a musician for 30+ years, glad I'm not the only one to notice the project name/logo mismatch! Close enough for PHP, I guess ;-)

**Comment by liuggio** [comment]
I think composer == conductor in PHP,
come on we are not saying triple equals.

**Comment by karikaariainen** [comment]
It is kind of ignorant to have a conductor depicting a composer.
