### ISSUE TITLE
composer.phar does not contain valid JSON

### ISSUE THREAD

**Issue by scrfix** [composer/getcomposer.org#43]
This just started today and I am hoping that someone can help fix this or at least point me in the correct direction.  I have installed composer and WAMP on a few Windows machines without issue.
I have a new Windows 7 computer.  I have installed the default settings of WAMP 64 bit with Apache 2.4.
I have added the following to the httpd.conf file:
AcceptFilter http none
AcceptFilter https none

I intalled git.
I intalled composer
I used the git clone to download Laravel.
I copied the composer.phar to the laravel installation directory.
When I run the command php composer install I get the error below.
When I run the command composer install I get the error below.
When I run the command php composer.phar install I get the same error as composer install returns to me.
when I run the command composer diag I get the same error as composer install returns to me.

Does anyone have a clue what this is?  I have tried to look up both errors with no results.  I have tried to download the previous alpha versions of the composer.phar file and they all do the same thing.  I have tested the version calls to ensure that git, composer and php are all working properly.  Can someone perhaps attach their working composer.phar if the forum allows it?  I have uninstalled and reinstalled composer multiple times.  I have installed and reinstalled laravel multiple times as well just in case.

COPY AND PASTE FROM COMMAND LINE
c:\wamp\l4beta5>php -v
PHP 5.4.3 (cli) (built: May 15 2012 01:01:59)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.2.0, Copyright (c) 2002-2012, by Derick Rethans

c:\wamp\l4beta5>git --version
git version 1.8.1.msysgit.1

c:\wamp\l4beta5>composer --version
Composer version 0209bd31a0ac3aeb2a68fc81e2d03c71072bef33

c:\wamp\l4beta5>php composer install
Could not open input file: composer

c:\wamp\l4beta5>composer install

  [Seld\JsonLint\ParsingException]
  "c:\wamp\l4beta5\composer.phar" does not contain valid JSON
  Parse error on line 1:
  #!/usr/bin/env php<
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-c
ustom-installers] [--no-scripts] [--no-progress] [-v|--verbose] [-o|--optimize-a
utoloader]

**Comment by SilkAndSlug** [comment]
For the benefit of future readers:

I also had this problem. In my case, I was calling Composer as a Cron job, via Phing. My crontab used a variable called COMPOSER. Renaming the variable to COMPOSER_BIN fixed my problem.

**Comment by Cperbony** [comment]
Same problem, resolved in Win Terminal, but does not work in CygWin64 terminal.

**Comment by shayan132476** [comment]
i have the same problem now
