### ISSUE TITLE
Please recommend users to install Composer globally

### ISSUE THREAD

**Issue by notpushkin** [composer/getcomposer.org#46]
I think the recommended installation method should be to install Composer globally.
1. It's the only working option on Windows.
2. That's what other package managers do (e.g. npm and gem).
3. This provides better command lines (`composer install` instead of `php composer.phar install`).
### Problem

Some libraries often provide 'installation instructions' that are easy to copy-paste, but are made for people with local installations. That's no good for global-lovers who need to _manually edit_ each command.

On the other side, if all commands were in form of `composer (anything)`, one with local installation could just `alias composer=php composer.phar` and execute these commands just as is.

**Comment by alcohol** [comment]
https://getcomposer.org/doc/00-intro.md#globally
