### ISSUE TITLE
Revisit the branding

### ISSUE THREAD

**Issue by gabrielbull** [composer/getcomposer.org#63]
In the same direction as Issue #38 , could we revisit the branding of Composer?

Here is something to start the discussion

![composer](https://f.cloud.github.com/assets/671923/2380909/2111d4ce-a8b5-11e3-93f1-9c6f51e391ed.jpg)

**Comment by vovafuckinkProg** [comment]
привет не  подскажете с чего начать мой уровень знаний 0
