### ISSUE TITLE
Installation instructions contain bad security habits

### ISSUE THREAD

**Issue by sarciszewski** [composer/getcomposer.org#76]
`curl https | php` needs to go. This was previously reported over a year ago in #41 and nobody has taken action.

This is what you need to do:

1. Generate an RSA/DSA/Ed25519/whatever asymmetric key pair. 
2. Keep your private key safe.
3. Sign your installer.
4. Publish your public key.
5. Publish amended install instructions that verify the signature before any code is run.

Then continue to verify the `.phar` from within the installer.

Not exactly rocket science, and not a low priority that you can really afford to keep sweeping under the rug while running off to conferences to drink beer and make lots of money while pushing an insecure solution.

**Comment by johnhunt** [comment]
+1 it's a shame sarciszewski is being ignored. Composer really needs this.

**Comment by jrobeson** [comment]
@sarciszewski : so how does one generate this key? maybe publishing a qiuck howto, so they just simply have to run a few commands to get the right key going.

**Comment by padraic** [comment]
All, see my comment at https://github.com/composer/getcomposer.org/issues/77

This should be pretty much everything that is required, and I now have it sitting in two independent packages I'll have finalised tomorrow. TLS support is reduced to one function. Self updating support is reduced to several methods. I honestly cannot make it any easier.

**Comment by sarciszewski** [comment]
> @sarciszewski : so how does one generate this key? maybe publishing a quick howto, so they just simply have to run a few commands to get the right key going.

* https://en.wikibooks.org/wiki/Cryptography/Generate_a_keypair_using_OpenSSL
* http://www.symantec.com/business/support/index?page=content&id=HOWTO41935

**Comment by BenCollver** [comment]
In the meanwhile, one could compare the file hash to the one published on slackbuilds.org.

http://slackbuilds.org/repository/14.1/development/composer/

**Comment by paragonie-scott** [comment]
The utility of a hash is very limited; what you want is a digital signature.

https://paragonie.com/blog/2015/08/you-wouldnt-base64-a-password-cryptography-decoded

**Comment by BenCollver** [comment]
With a hash you can verify integrity and authenticity [1].  A hash is one of the components of a digital signature [2].  Though a signature is better, a hash is what we have available today (vs. no verification at all.)

[1]
https://en.wikipedia.org/wiki/File_verification#Integrity_verification

[2]
https://en.wikipedia.org/wiki/Pretty_Good_Privacy#Digital_signatures

**Comment by paragonie-scott** [comment]
> With a hash you can verify integrity and authenticity [1].

Only if you include asymmetric-key cryptography of some sort, at which point you've just reinvented a digital signature.

> A hash is one of the components of a digital signature [2].

I'm well aware. 

For example, Ed25519 is a Schnorr digital signature scheme over an elliptic curve field that works by taking SHA512 of a message, splitting it in half, then using one half in place of a nonce and the other is used with the secret key to create a long digest that can be verified with the public key.

It probably wouldn't work without a 512-bit hash function.

But that doesn't mean that an SHA-512 hash is the same thing as an EdDSA signature. In most cases, verifying checksums from MD5, SHA1, etc. is little more than security theater.

**Comment by alcohol** [comment]
I can generate GPG signatures for the alpha releases if that would make people happy. It's a bit more secure than a md5/sha checksum.

**Comment by Seldaek** [comment]
Oh this is still open.
