### ISSUE TITLE
PDF doc not available 

### ISSUE THREAD

**Issue by llaville** [composer/getcomposer.org#81]
I got a 404 http error on link https://getcomposer.org/book.pdf

**Comment by Seldaek** [comment]
Yup there is a build failure in https://github.com/composer/getcomposer.org/blob/master/bin/make-pdf.sh

`! LaTeX Error: Environment Shaded undefined.`

If anyone can help look into this that'd be great as I have no clue about LaTeX and frankly not much time to investigate this..

All I know is the script requires the following packages on top of ubuntu 14.04 to run: pandoc, texlive-latex-base, texlive-latex-recommended, texlive-latex-extra, texlive-fonts-recommended, tex-gyre

But somehow it doesn't seem to be enough or something is outdated in the build script.

**Comment by stof** [comment]
Seems related to http://comments.gmane.org/gmane.text.pandoc/9206

**Comment by Seldaek** [comment]
Yeah I can google that error too, but then another one comes up, and another one, and so on, and I gave up because I don't see enough value in this PDF to dig in and fix it. If someone else can get the build to run again I will gladly merge a fix though.
