### ISSUE TITLE
Docs :) Possible addendum to the WIndows Install FAQ

### ISSUE THREAD

**Issue by twobob** [composer/getcomposer.org#90]
I noted that there quite a few instances where people have errant PHPRC variables in their Windows Environment path (from older PHP installs).

A quick note about "If the installer errors multiple times with the message Entry Point Not found for X then check your PHPRC Path in your environment variables points to your ACTUAL PHP install" would probably be helpful.

:) Many thanks

**Comment by Seldaek** [comment]
If you'd like to add that to the setup docs please send a pull request to https://github.com/composer/composer/blob/master/doc/00-intro.md#using-the-installer and/or https://github.com/composer/getcomposer.org/blob/master/views/download.html.twig#L25

**Comment by alcohol** [comment]
Does this apply to the Windows installer?

If so, @johnstevenson is this issue still applicable?

**Comment by johnstevenson** [comment]
@alcohol Please ignore the last comment - it is utter nonsense! I'll start again.

Composer-Setup doesn't look for a PHPRC variable, but simply reports the location of the loaded ini if something goes wrong. However, it would probably be better to mention the PHPRC variable if it is being used.

I've opened up an issue to do this: https://github.com/composer/windows-setup/issues/88

**Comment by alcohol** [comment]
Alright, thanks :-)

**Comment by johnstevenson** [comment]
Composer-Setup now handles the PHPRC variable - https://github.com/composer/windows-setup/commit/044f3e6c8fe1aada41046264369f6509960335bd
