### ISSUE TITLE
"composer update nothing" is not documented

### ISSUE THREAD

**Issue by ravage84** [composer/getcomposer.org#92]
It seems "composer update nothing" is an undocumented feature.
I found several blog posts and GH issues mentioning it, but I haven't found this documented at https://getcomposer.org/doc/03-cli.md#update

Blog post example:
http://www.lornajane.net/posts/2016/handling-composer-lock-file-out-of-date-warning

GH issue example:
https://github.com/composer/composer/issues/1751

I was wondering if it should not be documented as it is deprecated feature or something.

**Comment by alcohol** [comment]
`composer update nothing` is the same as `composer update --lock`

**Comment by ravage84** [comment]
I know, but nonethless it should be documented, IMO.

**Comment by alcohol** [comment]
`composer update --lock` is documented.

`composer update nothing`, while it works, is a novelty/legacy relic, and does not warrant documenting in my opinion.

**Comment by ravage84** [comment]
Good, let's tell the people not to use it by adding a short note to the composer update cli docs. :smirk_cat: 

Or even offiicially deprecate it in composer itself.

**Comment by stof** [comment]
``composer update nothing`` was just a hack before ``--lock`` was available actually. It is not a special composer feature allowing to update only the lock file. It is a partial update whitelisting only the ``nothing`` package (which is very unlikely to match any real package given the naming convention for packages).
So there is no reason to document it. It is just a smart way of using a documented feature (the partial update) to achieve something which was not yet a first-class citizen in composer at this time.
And there is also nothing to deprecate in Composer, as nothing was ever added in composer to support it.

Btw, as Composer is now smart when checking for outdated lock files (thanks to the ``content-hash`` introduced mid-2015), you probably don't need to perform lock-only updates now.

**Comment by Seldaek** [comment]
Yeah.. basically see my comment on lorna's post.

**Comment by Seldaek** [comment]
And just to expand a bit, `composer update ldskjldsjfsds` does the same as `composer update nothing`, but we're not going to document that either :)
