### ISSUE TITLE
The "/versions" url uses wrong content type

### ISSUE THREAD

**Issue by aik099** [composer/getcomposer.org#94]
The http://getcomposer.org/versions URL is using `application/octet-stream` content type instead of `application/json`. This results in browser attempting to download this page instead of showing formatted JSON response.

The page responds JSON now:

```json
{
    "stable": [{"path": "/download/1.0.0/composer.phar", "version": "1.0.0", "min-php": 50300}],
    "preview": [{"path": "/download/1.0.0/composer.phar", "version": "1.0.0", "min-php": 50300}],
    "snapshot": [{"path": "/composer.phar", "version": "40c14709f79f9d7ea35ac969cfbd7f41beb525bb", "min-php": 50300}]
}
```

**Comment by Seldaek** [comment]
https://getcomposer.org/versions serves as `application/json` now (it was text/plain before). `http://` should not be used.

**Comment by aik099** [comment]
> https://getcomposer.org/versions serves as application/json now (it was text/plain before).

Good.

> `http://` should not be used.

It is accessible so I can somebody can use it. The composer also has code inside it to use http:// or https:// depending on a setting.

**Comment by Seldaek** [comment]
Yes I just mean it doesn't matter IMO for browsers because browsers should use https:// for sure. Composer doesn't care about the content-type.

**Comment by aik099** [comment]
OK.
